# Form implementation generated from reading ui file 'signin.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 445)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(13, 13, 13);")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 310, 141, 41))
        self.pushButton.setStyleSheet("QPushButton{\n"
"font: 700 15pt \"Futura\";\n"
"color: rgb(173, 194, 255);\n"
"    background-color: rgb(51, 68, 95);\n"
"border-radius:20px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(101, 52, 255, 204);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(22, 22, 61, 189);\n"
"    color: rgb(219, 215, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 40, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 120, 61, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(250, 70, 261, 41))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    \n"
"border: 1px solid grey;\n"
"border-radius:20px;\n"
"    background-color: rgba(17, 17, 17, 245);\n"
"padding: 10px\n"
"\n"
"}\n"
"QLineEdit:hover{\n"
"border:1px solid white;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 150, 261, 41))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    \n"
"border: 1px solid grey;\n"
"border-radius:20px;\n"
"    background-color: rgba(17, 17, 17, 245);\n"
"padding: 10px\n"
"}\n"
"QLineEdit:hover{\n"
"border:1px solid white;\n"
"}\n"
"QLineEdit:pressed{\n"
"border:1px solid rgba(95, 139, 255, 219);\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(250, 230, 261, 41))
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"    \n"
"border: 1px solid grey;\n"
"border-radius:20px;\n"
"    background-color: rgba(17, 17, 17, 245);\n"
"padding: 10px\n"
"}\n"
"QLineEdit:hover{\n"
"border:1px solid white;\n"
"}\n"
"QLineEdit:pressed{\n"
"border:1px solid rgba(95, 139, 255, 219);\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 210, 71, 16))
        self.label_4.setObjectName("label_4")
        self.message = QtWidgets.QLabel(parent=self.centralwidget)
        self.message.setGeometry(QtCore.QRect(250, 280, 251, 20))
        self.message.setText("")
        self.message.setObjectName("message")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Sign In"))
        self.label_2.setText(_translate("MainWindow", "Username"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.label_4.setText(_translate("MainWindow", "Preference"))
