# Form implementation generated from reading ui file 'Userwindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 445)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(13, 13, 13);")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stopButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(330, 240, 141, 41))
        self.stopButton.setStyleSheet("QPushButton{\n"
"font: 700 15pt \"Futura\";\n"
"    color: rgb(218, 125, 125);\n"
"    background-color: rgb(171, 74, 69);\n"
"border-radius:20px\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(211, 50, 57);\n"
"}\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(77, 24, 23);\n"
"    color: rgb(219, 215, 255);\n"
"}")
        self.stopButton.setObjectName("stopButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
